server:
  #  port: ${PORT:${SERVER_PORT:0}}
  port: 8082
spring:
  application:
    name: api-catalog
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movies-dev
    username: usr-movies
    password: pwd-movies
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/