server:
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8082
spring:
  application:
    name: api-catalog

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${random.int}